### ISSUE TITLE
Current state of the optimizer

### ISSUE THREAD

**Issue by rjschmitt** [cybertronai/pytorch-lamb#8]
Hey,

thank you for sharing that code. I'm not totally aware of the current status, but only found hints to v3 of the paper. As for now, they released v5 at ICLR 2020. Is the current implementation according to that version?

Kind regards,
Raphael

**Comment by 8enmann** [comment]
Has not been updated, PRs welcome

**Comment by 8enmann** [comment]
Author open sourced TF version
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/lamb.py

**Comment by rjschmitt** [comment]
Thank you! :)

**Comment by rjschmitt** [comment]
Is there a possibility to use the TF-version within pytorch or does it require an extra implementation?

**Comment by 8enmann** [comment]
Not possible without a rewrite :/
ᐧ
